# Global settings
testLimit: 50000
seqLen: 100
coverage: true
corpusDir: echidna-corpus
gasLimit: 8000000
balanceAddr: 0xffffffff
propMaxGas: 8000030
testMaxGas: 8000030

# Specify multiple sender addresses
sender: ["0x10000", "0x20000", "0x30000"]

# Enable shrinking of failed test cases
shrinkLimit: 5000

# Remove the initialize field if you don't need it
# If you do need it, specify it as a string, for example:
# initialize: "contractName.initializeFunction()"

# Use fuzzing mode
testMode: assertion

# Output format
format: text

# Specify any constants you want to use in your tests
constants: []
