name: Smart Contract CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install Solidity linters
        run: |
          npm install -g solhint
          npm install -g ethlint

      - name: Run Solhint
        run: solhint 'contracts/**/*.sol'

      - name: Run Ethlint
        run: solium -d contracts/

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Hardhat tests
        run: npx hardhat test

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Slither
        run: |
          pip3 install slither-analyzer
          pip3 install solc-select
          solc-select install 0.8.19
          solc-select use 0.8.19

      - name: Run Slither
        run: slither . --hardhat-ignore-compile

      - name: Install Echidna
        run: |
          sudo apt-get update
          sudo apt-get install -y echidna

      - name: Run Echidna
        run: |
          for file in contracts/*.sol; do
            echidna-test $file --contract $(basename $file .sol) --config echidna.config.yml || true
          done
